services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: linkkari
      POSTGRES_PASSWORD: kissa123
      POSTGRES_DB: linkki_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U linkkari"]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    build: .
    image: linkkibot:latest
    restart: on-failure
    env_file: .env
    depends_on:
    - db:
      condition: service_healthy
      restart: true
    stdin_open: true
    tty: true
    command: ["--modes", "month"]

volumes:
  db_data:
